const { chromium } = require('playwright');
const fs = require('node:fs');
const path = require('node:path');

(async () => {
  const browser = await chromium.launch({ channel: 'chrome', headless: true, args: ['--enable-unsafe-swiftshader'] });
  const errors = [];
  const checks = [];
  try {
    const page = await browser.newPage({ viewport: { width: 1200, height: 800 } });
    page.on('pageerror', error => errors.push(String(error)));
    page.on('console', message => { if (message.type() === 'error' && !message.text().startsWith('Failed to load resource:')) errors.push(message.text()); });
    page.on('response', response => { if (response.status() >= 400 && !response.url().endsWith('/favicon.ico')) errors.push(`${response.status()} ${response.url()}`); });
    const state = () => page.evaluate(() => window.planetWorldState);
    await page.goto('http://127.0.0.1:8765/index.html?minimap');
    await page.waitForFunction(() => window.planetWorldState?.minimap_location, null, { timeout: 240000 });
    let before = await state();
    await page.mouse.move(790, 370);
    await page.mouse.down({ button: 'left' });
    await page.waitForFunction(() => window.planetWorldState.dragging, null, { timeout: 30000 });
    await page.mouse.move(925, 408, { steps: 8 });
    await page.waitForFunction(yaw => Math.abs(window.planetWorldState.yaw - yaw) > .05, before.yaw, { timeout: 30000 });
    await page.mouse.up({ button: 'left' });
    await page.waitForFunction(() => !window.planetWorldState.dragging);
    checks.push({ test: 'Real left-button overview drag', state: await state() });
    before = await state();
    await page.mouse.move(980, 430, { steps: 4 });
    await page.waitForTimeout(800);
    if (Math.abs((await state()).yaw - before.yaw) > .001) throw new Error('Camera kept rotating after left release');
    checks.push({ test: 'Release stops drag', passed: true });
    await page.screenshot({ path: path.resolve(__dirname, '../deliverables/minimap-web-overview.png'), timeout: 60000 });
    await page.keyboard.press('Tab');
    await page.waitForFunction(() => !window.planetWorldState.overview);
    before = await state();
    await page.mouse.move(790, 370);
    await page.mouse.down({ button: 'left' });
    await page.waitForFunction(() => window.planetWorldState.dragging);
    await page.mouse.move(930, 400, { steps: 8 });
    await page.waitForFunction(heading => Math.hypot(...window.planetWorldState.heading.map((value, i) => value - heading[i])) > .08, before.heading, { timeout: 30000 });
    await page.mouse.up({ button: 'left' });
    await page.waitForFunction(() => !window.planetWorldState.dragging);
    checks.push({ test: 'Real left-button roaming drag', state: await state() });
    await page.keyboard.down('w');
    await page.waitForTimeout(900);
    await page.keyboard.up('w');
    await page.waitForTimeout(700);
    await page.screenshot({ path: path.resolve(__dirname, '../deliverables/minimap-web-roaming.png'), timeout: 60000 });
    before = await state();
    const canvas = await page.locator('#canvas').boundingBox();
    await page.mouse.click(canvas.x + before.destination_button[0] * canvas.width, canvas.y + before.destination_button[1] * canvas.height);
    await page.waitForFunction(() => window.planetWorldState.destinations_open, null, { timeout: 30000 });
    if ((await state()).dragging) throw new Error('Menu click incorrectly started left drag');
    checks.push({ test: 'Menu click opens panel without rotating', passed: true });
    await page.screenshot({ path: path.resolve(__dirname, '../deliverables/minimap-web-menu.png'), timeout: 60000 });
    fs.writeFileSync(path.resolve(__dirname, '../deliverables/minimap-browser-review.json'), JSON.stringify({ checked_at: new Date().toISOString(), errors, checks }, null, 2));
    if (errors.length) throw new Error(JSON.stringify(errors));
    console.log('MINIMAP_LEFT_DRAG_BROWSER_OK', checks.length);
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
